### ISSUE TITLE
Helveticons, licensing and forks

### ISSUE THREAD

**Issue by jbergstroem** [pengwynn/fumblr#5]
Hello,
just found out that you checked in Helveticons a good while ago, under your own license. It seems that you corrected this, but the forks seems to still have them. Not sure what the best way to handle this situation would be, so it felt best to start with the $source.

To clarify: Helveticons is a icon set purchased at http://helveticons.ch. Icons are purchased individually and are not to be shared or relicensed.

How do you think its best to proceed?

**Comment by pengwynn** [comment]
My sincerest apologies. It appears that our fork under TheChangelog account was made public by mistake. It is now private. Looking at the network graph, it appears only one Fumblr fork is a fork of that repo and I have reached out to them to remove the assets.

Please email me directly if you have additional concerns and we'll work to correct the problem.
